/**
* FavouriteList API
* Get, delete, update favourite airlines
*
* OpenAPI spec version: 1.0.0
* Contact: hotzipeti@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models


/**
 * 
 * @param airlines 
 */
data class Favourites (
    val airlines: kotlin.Array<kotlin.String>? = null
) {

}

